# Generated by Django 4.2.1 on 2023-06-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_item_file_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('PK', 'Sample pack'), ('PL', 'Plugin'), ('PR', 'VST Presets')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
